### ISSUE TITLE
keyboard assignment improvement

### ISSUE THREAD

**Issue by lenvdb** [VerticalLongboard/xplane-vhf-helper#2]
Dear Sir love your VR-Radio-Helper.

Noticed a small mistake when assigning Keyboard shortcut from X Plane.
In module Singletons\loop.lua create command "FlyWithLua/" .. Globals.readableScriptName .. "/TogglePanel", 
I have replaced it with "FlyWithLua/VR_Radio_Helper/TogglePanel", which sorts the problem.

A suggestion for both  Com/Nav to have a button to swop Com1/Com2 and Nav1/Nav2 frequencies as on the Radio.

Thanks for you efforts

Len

**Comment by VerticalLongboard** [comment]
Thanks a lot! I fixed it in https://github.com/VerticalLongboard/xplane-vhf-helper/releases/tag/1.1.8 and added the Swap button to the backlog via https://github.com/VerticalLongboard/xplane-vhf-helper/projects/1#card-54675099

Have a great day!
